# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab56abeb9854313e1aab0e9eb6adc85b585baa6b12589ab83bbaea8a1cd479b024bdd51db8ae10cfd4d5ffc455290d52b66495c86c3bec9ac7aaa9c17d283536

test:
  secret_key_base: 3f80ce7747a9a71bf44c5c677d00d73feb06ec5fb4da8d4af8130997c0a583d05cceadc7fa62def5dc9ea3c33fc3f8a50a1e367017a545b6184a3931f4defec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
